### ISSUE TITLE
Add support for Grails 3.x

### ISSUE THREAD

**Issue by ghost** [budjb/grails-jersey-request-builder#25]
Grails 3 is here - requesting support/compatibility/documentation for Grails 3 apps!

**Comment by budjb** [comment]
I will not be porting this plugin to Grails 3.x. I wasn't terribly happy with some of the decisions I had made with this plugin, and decided to create something new and a bit more portable. The `http-requests` library is the spiritual successor to this one. You can find info about it here: https://bintray.com/budjb/grails-plugins/http-requests-grails/view#read

The plugin is available via the Grails bintray repository for Grails 3. Support for both Jersey Client 1.x and Jersey Client 2.x are available.
